# Generated by Django 4.2.23 on 2025-08-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strtime', models.DateTimeField()),
                ('title', models.TextField()),
                ('tasktime', models.TextField()),
                ('taskdetails', models.TextField()),
                ('detailtime', models.TextField()),
                ('endtime', models.DateTimeField()),
                ('goal', models.TextField()),
                ('feeling', models.CharField(choices=[('fulfilled', 'Fulfilled'), ('energized', 'Energized'), ('focused', 'Focused'), ('neutral', 'Neutral'), ('tired', 'Tired'), ('stressed', 'Stressed'), ('frustrated', 'Frustrated')], default='neutral', help_text='How did you feel during/after this activity?', max_length=50)),
            ],
            options={
                'db_table': 'final_diary_2',
            },
        ),
    ]
