# Generated by Django 4.2.23 on 2025-07-11 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='goal',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='detailtime',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='tasktime',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='diaryentry',
            table='final_diary',
        ),
    ]
