# Generated by Django 4.2.23 on 2025-08-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diaryentry',
            table='final_diary',
        ),
    ]
