# Generated by Django 4.2.23 on 2025-07-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_diaryentry_goal_alter_diaryentry_detailtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='feeling',
            field=models.CharField(choices=[('fulfilled', 'Fulfilled'), ('energized', 'Energized'), ('focused', 'Focused'), ('neutral', 'Neutral'), ('tired', 'Tired'), ('stressed', 'Stressed'), ('frustrated', 'Frustrated')], default='neutral', help_text='How did you feel during/after this activity?', max_length=50),
        ),
    ]
